author: Dale Zak
name: github-to-trello-card
description: GitHub Action to integrate Github to Trello
branding:
  icon: 'check-square'
  color: 'gray-dark'
inputs:
  trello-api-key:
    description: Trello API key, visit https://trello.com/app-key for key
    required: true
  trello-auth-token:
    description: Trello auth token, visit https://trello.com/app-key then click generate a token
    required: true
  trello-board-id:
    description: Trello board ID, visit a board then append .json to url to find id
    required: true
  trello-card-action:
    description: Trello card action i.e. "Attach PR", "PR merged"
    required: true
  trello-list-name:
    description: Trello list name for card designation e.g. "Ready to Deploy"
    required: false
runs:
  using: node12
  main: dist/index.js
